/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import strapiPluginMoesif from "strapi-plugin-moesif/strapi-admin";
import htmlViewer from "../../src/plugins/html-viewer/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    documentation: documentation,
    i18n: i18N,
    sentry: sentry,
    "users-permissions": usersPermissions,
    "config-sync": configSync,
    "strapi-plugin-moesif": strapiPluginMoesif,
    "html-viewer": htmlViewer,
  },
});
