export const GENERAL_ALLOWED_UPLOAD_MIME_TYPES = [
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
  'image/bmp',
  'image/avif',
  'image/vnd.microsoft.icon',
  'image/tiff',
  'video/mpeg',
  'video/mp4',
  'video/x-msvideo',
  'video/ogg',
  'video/mp2t',
  'video/webm',
  'video/3gpp',
  'video/3gpp2',
  'video/quicktime',
  'video/vnd.avi',
  'audio/3gpp',
  'audio/webm',
  'audio/3gpp2',
  'audio/aac',
  'audio/midi',
  'audio/mpeg',
  'audio/ogg',
  'audio/opus',
  'audio/wav',
  'application/pdf',
];

export const ALLOWED_UPLOAD_MIME_TYPES_FOR_STRAPI_USERS = [
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'image/svg+xml',
  'application/xml',
];
