const MRT_Localization_AR = {
  actions: 'أدوات',
  and: 'و',
  cancel: 'إلغاء',
  changeFilterMode: 'تغيير وضع التصفية',
  changeSearchMode: 'تغيير وضع البحث',
  clearFilter: 'مسح التصفية',
  clearSearch: 'مسح البحث',
  clearSort: 'مسح الترتيب',
  clickToCopy: 'انقر للنسخ',
  collapse: 'طي',
  collapseAll: 'طي الكل',
  columnActions: 'إجراءات العمود',
  copiedToClipboard: 'تم النسخ إلى الحافظة',
  dropToGroupBy: 'اسحب للتجميع حسب {column}',
  edit: 'تعديل',
  expand: 'توسيع',
  expandAll: 'توسيع الكل',
  filterArrIncludes: 'يتضمن',
  filterArrIncludesAll: 'يتضمن الكل',
  filterArrIncludesSome: 'يتضمن بعضها',
  filterBetween: 'بين',
  filterBetweenInclusive: 'بين (شامل)',
  filterByColumn: 'بحث بـ{column}',
  filterContains: 'يحتوي على',
  filterEmpty: 'فارغ',
  filterEndsWith: 'ينتهي بـ',
  filterEquals: 'يساوي',
  filterEqualsString: 'يساوي',
  filterFuzzy: 'مشابه لـ',
  filterGreaterThan: 'أكبر من',
  filterGreaterThanOrEqualTo: 'أكبر من أو يساوي',
  filterInNumberRange: 'في نطاق الأرقام',
  filterIncludesString: 'يتضمن',
  filterIncludesStringSensitive: 'يتضمن (حساس لحالة الأحرف)',
  filterLessThan: 'أقل من',
  filterLessThanOrEqualTo: 'أقل من أو يساوي',
  filterMode: 'فلتر حسب : {filterType}',
  filterNotEmpty: 'غير فارغ',
  filterNotEquals: 'لا يساوي',
  filterStartsWith: 'يبدأ بـ',
  filterWeakEquals: 'يساوي (ضعيف)',
  filteringByColumn:
    'Filtrováno podle sloupce {column} - {filterType} {filterValue}',
  goToFirstPage: 'اذهب إلى الصفحة الأولى',
  goToLastPage: 'اذهب إلى الصفحة الأخيرة',
  goToNextPage: 'الصفحة التالية',
  goToPreviousPage: 'الصفحة السابقة',
  grab: 'امسك',
  groupByColumn: 'Group by : {column}',
  groupedBy: 'مجمعة بواسطة:',
  hideAll: 'إخفاء الكل',
  hideColumn: 'إخفاء {column}',
  max: 'Max.',
  min: 'Min.',
  move: 'تحريك',
  noRecordsToDisplay: 'لا توجد بيانات للعرض',
  noResultsFound: 'لم يتم العثور على نتائج',
  of: 'من',
  or: 'أو',
  pinToLeft: 'تثبيت إلى اليمين',
  pinToRight: 'تثبيت إلى اليسار',
  resetColumnSize: 'إعادة تعيين حجم العمود',
  resetOrder: 'إعادة تعيين الترتيب',
  rowActions: 'إجراءات الصف',
  rowNumber: '#',
  rowNumbers: 'أرقام الصفوف',
  rowsPerPage: 'عدد الصفوف في الصفحة:',
  save: 'حفظ',
  search: 'بحث',
  selectedCountOfRowCountRowsSelected:
    'تم تحديد {selectedCount} من أصل {rowCount} صف',
  select: 'تحديد',
  showAll: 'إظهار الكل',
  showAllColumns: 'إظهار جميع الأعمدة',
  showHideColumns: 'إظهار / إخفاء الأعمدة',
  showHideFilters: 'إظهار / إخفاء التصفية',
  showHideSearch: 'إظهار / إخفاء البحث',
  sortByColumnAsc: 'ترتيب {column} تصاعديًا',
  sortByColumnDesc: 'ترتيب {column} تنازليًا',
  sortedByColumnAsc: 'مرتب {column} تصاعديًا',
  sortedByColumnDesc: 'مرتب {column} تنازليًا',
  thenBy: 'ثم بواسطة',
  toggleDensity: 'كثافة العرض',
  toggleFullScreen: 'تبديل ملء الشاشة',
  toggleSelectAll: 'تحديد الكل',
  toggleSelectRow: 'تحديد الصف',
  toggleVisibility: 'تبديل الرؤية',
  ungroupByColumn: 'ازالة تجميع {column}',
  unpin: 'إزالة التثبيت',
  unpinAll: 'إزالة التثبيت عن الكل',
  unsorted: 'غير مرتب',
};

export { MRT_Localization_AR };
//# sourceMappingURL=cs.esm.js.map
